include: package:flutter_lints/flutter.yaml

linter:
  rules:
    use_super_parameters: true
    camel_case_types: true
    empty_statements: false
    prefer_relative_imports: true
    avoid_type_to_string: true
    avoid_types_as_parameter_names: true
    avoid_print: false
    prefer_single_quotes: true
    cancel_subscriptions: true
    comment_references: true
